
spring:
  application:
    name: itoken-service-redis



  boot:
    admin:
      client:
        url: http://192.168.1.4:8084

  zipkin:
    base-url: http://192.168.1.4:9411


  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.1.4:26379, 192.168.1.4:26380, 192.168.1.4:26381

server:
  port: 8502



eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.4:8761/eureka/,http://192.168.1.4:8861/eureka/,http://192.168.1.4:8961/eureka/


management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    web:
      server:
        auto-time-requests: false
